### ISSUE TITLE
Just gives me a binary file

### ISSUE THREAD

**Issue by TheTechRobo** [akx/cachemoney#2]
This just outputs a binary file for me. What do I do with it?

**Comment by akx** [comment]
What was the command you ran and the target you ran it against, and what was the output file?

**Comment by TheTechRobo** [comment]
I ran this command: 

```
python3 -m cachemoney --cache-dir ../.cache/chromium/Default/Cache/ --output-root files --filter "*ohmyzsh/stargazers"
```

Output file: https://transfer.archivete.am/qvDLF/stargazers

I'm not sure what you mean by target.

I successfully extracted it with NirSoft's chrome cache extractor (through WINE), if that helps.

**Comment by dataphile-uk** [comment]
I've found the extracted files to be gzip compressed

**Comment by TheTechRobo** [comment]
Oh, that would actually make sense.

**Comment by akx** [comment]
By "target" I meant "Chromium" in this case :)

@dataphile-uk Thanks for the heads-up – that may have changed since I first wrote this program :)

**Comment by akx** [comment]
@TheTechRobo @dataphile-uk Looks like recent Chromes indeed gzip _some_ of the files on disk. If you pull the newest `master` version, you'll find a new `--decompress` switch :)

**Comment by TheTechRobo** [comment]
I can't confirm that the new --decompress switch works, as I'm not sure if the things I'm extracting needed to be decompressed, but I can confirm that decompressing the old extracted file I reported with with gzip works. :D

**Comment by akx** [comment]
Glad it did the trick for you!
